refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[ 📅 {d(%Y-%m-%d %H:%M:%S%.f)} | {l} | {M}:{L} ] {n}{n}{m}{n}{n}{n}"
  all:
    kind: rolling_file
    path: "log/portfolio-rs.log"
    encoder:
      pattern: "[ 📅 {d(%Y-%m-%d %H:%M:%S%.f)} | {l} | {M}:{L} ] {n}{n}{m}{n}{n}{n}"
    policy:
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "log/old/portfolio-rs-{}.log"
root:
  level: info
  appenders:
    - stdout
    - all